let walletsData = [
  {
    id: "1",
    name: "Bank",
    budget: 500,
    budgetInterval: "month",
    transactions: [
      {
        id: "1",
        name: "Burger King",
        type: "Expense",
        category: 2,
        date: "2024-10-10",
        amount: "9.45",
        notes: "",
      },
      {
        id: "2",
        name: "Dentist",
        type: "Expense",
        category: 1,
        date: "2024-09-10",
        amount: "50",
        notes: "",
      },
      {
        id: "3",
        name: "Sleeping Pill",
        type: "Expense",
        category: 4,
        date: "2024-10-23",
        amount: "11.5",
        notes: "",
      },
      {
        id: "4",
        name: "Salary",
        type: "Earning",
        category: 6,
        date: "2024-10-01",
        amount: "1500",
        notes: "",
      },
      {
        id: "5",
        name: "Salary",
        type: "Earning",
        category: 6,
        date: "2024-09-01",
        amount: "1500",
        notes: "",
      },
      {
        id: "6",
        name: "Salary",
        type: "Earning",
        category: 6,
        date: "2023-08-25",
        amount: "1500",
        notes: "",
      },
    ],
  },

  {
    id: "2",
    name: "Savings",
    transactions: [
      {
        id: "1",
        name: "Burger King",
        type: "Expense",
        category: 1,
        date: "2024-10-10",
        amount: "150",
        notes: "",
      },
      {
        id: "2",
        name: "Burger King",
        type: "Earning",
        category: 5,
        date: "2024-10-10",
        amount: "150",
        notes: "",
      },
    ],
  },
  {
    id: "3",
    name: "House",
    transactions: [
      {
        id: "1",
        name: "Burger King",
        type: "Expense",
        category: 2,
        date: "2024-10-10",
        amount: "150",
        notes: "",
      },
      {
        id: "2",
        name: "Burger King",
        type: "Earning",
        category: 2,
        date: "2024-10-10",
        amount: "150",
        notes: "",
      },
    ],
  },
];

export default walletsData;
